// <auto-generated />
namespace MrConstruction.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removedisBeforeandisAfterfromUploads : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removedisBeforeandisAfterfromUploads));
        
        string IMigrationMetadata.Id
        {
            get { return "201602230120091_removed isBefore and isAfter from Uploads"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
